SELECT
	E.ADMIN_ID 
FROM
	(
	SELECT
		A.ADMIN_ID,
		( SELECT COUNT( O.ADMIN_ID ) FROM ORDER_LIST O WHERE O.ADMIN_ID = A.ADMIN_ID AND O.RECEIVED_DATE IS NULL ) CNT 
	FROM
		ADMIN A 
	) E 
WHERE
	E.CNT = (
	SELECT
		MIN( F.CNT ) 
	FROM
		(
		SELECT
			A.ADMIN_ID,
			( SELECT COUNT( O.ADMIN_ID ) FROM ORDER_LIST O WHERE O.ADMIN_ID = A.ADMIN_ID AND O.RECEIVED_DATE IS NULL ) CNT 
		FROM
			ADMIN A 
		) F 
	);