CREATE TABLE CART_DETAILS(
		cart_id INTEGER NOT NULL,
		book_id INTEGER NOT NULL,
		quantity INTEGER DEFAULT 1,
		CONSTRAINT CART_DETAILS_PK PRIMARY KEY(cart_id,book_id),
		CONSTRAINT CART_DETAILS_USER_FK FOREIGN KEY(cart_id) REFERENCES CUSTOMER(user_id)
		ON DELETE CASCADE,
		CONSTRAINT CART_DETAILS_BOOK_FK FOREIGN KEY(book_id) REFERENCES BOOK(book_id)
		ON DELETE CASCADE
);