CREATE TABLE ADMIN(
		admin_id INTEGER NOT NULL,
		user_name VARCHAR2(128) NOT NULL UNIQUE,
		first_name VARCHAR2(128) NOT NULL,
		last_name VARCHAR2(128) NOT NULL,
		email VARCHAR2(128) NOT NULL,
		password VARCHAR2(512) NOT NULL,
		phone VARCHAR2(30) NOT NULL,
		CONSTRAINT ADMIN_PK PRIMARY KEY (admin_id)
);
