CREATE TABLE CART(
		cart_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		book_id INTEGER NOT NULL,
		quantity INTEGER DEFAULT 1,
		CONSTRAINT CART_PK PRIMARY KEY(cart_id),
		CONSTRAINT CART_USER_FK FOREIGN KEY(user_id) REFERENCES CUSTOMER(		user_id) ON DELETE CASCADE,
		CONSTRAINT CART_BOOK_FK FOREIGN KEY(book_id) REFERENCES BOOK(book_id)
		ON DELETE CASCADE

);