-- DROP TABLE ADDRESS_DETAIL;
-- DROP TABLE CUSTOMER;


CREATE TABLE CUSTOMER(
		user_id INTEGER NOT NULL,
		user_name VARCHAR2(512) NOT NULL UNIQUE,
		first_name VARCHAR2(512) NOT NULL,
		last_name VARCHAR2(512) NOT NULL,
		email VARCHAR2(128) NOT NULL,
		password VARCHAR2(512) NOT NULL,
		signup_date DATE DEFAULT SYSDATE,
		total_bought INTEGER DEFAULT 0,
		CONSTRAINT CUSTOMER_PK PRIMARY KEY (user_id)
);

CREATE TABLE ADDRESS_DETAIL(
		user_id INTEGER NOT NULL,
		address_1 VARCHAR2(512) ,
		address_2 VARCHAR2(512) ,
		city VARCHAR2(128) NOT NULL,
		country VARCHAR2(128) NOT NULL,
		phone VARCHAR2(30) NOT NULL,
		CONSTRAINT ADDRESS_DETAIL_PK PRIMARY KEY (user_id),
		CONSTRAINT ADDRESS_DETAIL_USER_FK FOREIGN KEY (user_id) REFERENCES CUSTOMER(user_id) ON DELETE CASCADE
);








