CREATE TABLE ORDER_DETAIL(
	order_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	book_id INTEGER NOT NULL,
	admin_id INTEGER NOT NULL,
	order_date DATE DEFAULT SYSDATE,
	order_status VARCHAR2(12) DEFAULT 'PENDING',
	received_date DATE,
	CONSTRAINT ORDER_DETAIL_PK PRIMARY KEY(order_id),
		CONSTRAINT ORDER_DETAIL_USER_FK FOREIGN KEY(user_id) REFERENCES CUSTOMER(user_id) ON DELETE CASCADE,
		CONSTRAINT ORDER_DETAIL_ADMIN_FK FOREIGN KEY(admin_id) REFERENCES ADMIN(admin_id) ON DELETE CASCADE,
		CONSTRAINT ORDER_DETAIL_BOOK_FK FOREIGN KEY(book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE

);