CREATE TABLE DISCOUNT_TOKEN(
	token_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	admin_id INTEGER NOT NULL,
	creation_date DATE DEFAULT SYSDATE,
	expire_date DATE NOT NULL,
	can_use INTEGER DEFAULT 1,
	minimum_order INTEGER DEFAULT 0,
	discount_percentage INTEGER NOT NULL,
	CONSTRAINT DISCOUNT_TOKEN_PK PRIMARY KEY(token_id),
		CONSTRAINT DISCOUNT_TOKEN_USER_FK FOREIGN KEY(user_id) REFERENCES CUSTOMER(		user_id) ON DELETE CASCADE,
		CONSTRAINT DISCOUNT_TOKEN_ADMIN_FK FOREIGN KEY(admin_id) REFERENCES ADMIN(		admin_id) ON DELETE CASCADE

);