CREATE OR REPLACE TRIGGER UPDATE_RATINGS_TWO
AFTER UPDATE 
ON REVIEW
FOR EACH ROW
DECLARE 
	ID INTEGER;
	R NUMBER;
	S NUMBER;
	X NUMBER;
	Y NUMBER;
	Z NUMBER;
	PRV NUMBER;
BEGIN
	ID := :OLD.BOOK_ID;
	R := :OLD.RATINGS;
	S := :NEW.RATINGS;
	SELECT RATINGS INTO X  FROM BOOK WHERE BOOK_ID = ID;
	SELECT NO_OF_RATINGS INTO Y  FROM BOOK WHERE BOOK_ID = ID;
	PRV := (X*Y - R)/(Y-1);
	Z := ( (PRV*(Y-1) )+ S )/(Y);
	UPDATE BOOK SET RATINGS = Z WHERE BOOK_ID = ID;
END;
/