CREATE OR REPLACE TRIGGER UPDATE_RATINGS
AFTER INSERT 
ON REVIEW
FOR EACH ROW
DECLARE 
	ID INTEGER;
	R NUMBER;
	X NUMBER;
	Y NUMBER;
	Z NUMBER;
BEGIN
	ID := :NEW.BOOK_ID;
	R := :NEW.RATINGS;
	SELECT RATINGS INTO X  FROM BOOK WHERE BOOK_ID = ID;
	SELECT NO_OF_RATINGS INTO Y  FROM BOOK WHERE BOOK_ID = ID;
	Z := ( (X*Y)+ R )/(Y+1);
	UPDATE BOOK SET RATINGS = Z,NO_OF_RATINGS = NO_OF_RATINGS + 1 WHERE BOOK_ID = ID;
END;
/