CREATE OR REPLACE PROCEDURE DELETE_PUBLISHER (ID IN INTEGER) IS
	BID INTEGER;
	
BEGIN
	FOR R IN (SELECT BOOK_ID FROM BOOK WHERE PUBLISHER_ID = ID)
	LOOP
		DELETE FROM BOOK WHERE BOOK_ID = R.BOOK_ID;
	END LOOP;
	DELETE FROM PUBLISHER WHERE PUBLISHER_ID = ID;
	COMMIT;
EXCEPTION
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('Some unknown error occurred.') ;
END;
/